services:
  - type: web
    name: runlog-backend
    runtime: python
    buildCommand: ""
    startCommand: pserve development.ini --server-name main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: runlog-db
          property: connectionString

databases:
  - name: runlog-db
